Branch pe d changes
AY2122S2-CS2103T-W15-1/tp pull request #255
Opened 2022-04-07 04:42 UTC by Justinnje

2022-04-07 08:17 UTC, e0543517 requested changes
LGTM other than some minor suggestions.

2022-04-07 08:17 UTC, e0543517 commented on src/main/java/seedu/address/model/applicant/Applicant.java
> -                && otherApplicant.getName().equals(getName());
Slight error in java doc.

2022-04-07 08:17 UTC, e0543517 commented on src/main/java/seedu/address/model/applicant/Applicant.java
> +                && otherApplicant.getNric().equals(getNric())
Should this be `||` instead of `&&`?

2022-04-08 03:42 UTC, seanleong339 approved these changes
LGTM

2022-04-08 09:26 UTC, e0543517 approved these changes
LGTM

2022-04-08 09:26 UTC, merged