Branch delete applicant command draft
AY2122S2-CS2103T-W15-1/tp pull request #86
Opened 2022-03-09 10:25 UTC by e0543517

2022-03-11 05:57 UTC, e0543517 reviewed
Todo: Change to use index to access the list instead of id.

2022-03-12 07:36 UTC, seanleong339 requested changes
Minor change to MESSAGE_USAGE required, everything else LGTM

2022-03-12 07:36 UTC, seanleong339 commented on src/main/java/seedu/address/logic/commands/applicant/DeleteApplicantCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD
Change to index?

2022-03-12 07:39 UTC, e0543517 commented on src/main/java/seedu/address/logic/commands/applicant/DeleteApplicantCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD
Done.

2022-03-12 07:41 UTC, seanleong339 approved these changes
LGTM

2022-03-12 07:42 UTC, merged